### ISSUE TITLE
"It's" vs. "its" Problems

### ISSUE THREAD

**Issue by nobozo** [llogiq/llogiq.github.io#11]
Your page about the differences between Java and Rust has at least 2 "it's" vs. "its" errors.

**Comment by llogiq** [comment]
Thanks. I hopefully caught all of them.

**Comment by nobozo** [comment]
On 2/29/2016 12:31 PM, llogiq wrote:

> Thanks. I hopefully caught all of them.

I checked and I think you did.

Jon
