### ISSUE TITLE
Broken inline HTML

### ISSUE THREAD

**Issue by badboy** [llogiq/llogiq.github.io#16]
In your recent post, the HTML is rendered incorrectly.
This: https://github.com/llogiq/llogiq.github.io/commit/7893166e610d93495be8c38cf1d04f9535438980#diff-44f403c1bee078848e6890feebfbef9aR36

looks like this:
![](https://tmp.fnordig.de/scr/47403fb493.png)

**Comment by llogiq** [comment]
I think this was fixed for a long time. Closing.
