### ISSUE TITLE
Comments through Hash

### ISSUE THREAD

**Issue by Stebalien** [llogiq/llogiq.github.io#3]
Here are some disorganized comments (through Hash). I'm not an expert so some of my comments may not be completely correct.

> OIBIT

Maybe you shouldn't expand this... OIBIT traits are actually opt-out and don't even have to be built-in (IIRC).

> Since Eq is basically empty (apart from a pre-defined marker method), auto-deriving has no chance of doing something interesting, so it won't.

What marker method?

> The Index and IndexMut traits specify the indexing operation, e.g. x[y] and x[y] = z, respectively (well the latter is a lie, IndexMut does not actually assign the value, but returns an lvalue ready for assigning).

More importantly, IndexMut returns a mutable reference (sort of). You can not only assign but can mutate in-place.

> the Fn*-traits abstract the act of calling something. The difference between those traits is simply how the self is taken: Fn takes it by reference, FnMut by mutable reference and FnOnce consumes it directly (which is after all why it can only be called once, as there is no self to call afterwards).

For consistency, I'd say that `FnOnce` consumes it by-value. Also, it might be worth mentioning that these traits can't be implemented manually in stable rust.

> Display and Debug are used for formatting values <ins>for display</ins><del>, respectively</del>.

Opinionated nits.

> Should you decide to implement Debug manually, you may want to distinguish between the normal {:?} format specifier and the pretty-printing {:#?} one. You can do this by querying the Formatter::flags() method, which will have the 4 bit set (which I found out by experiment). Thus, if (f.flags() & 4) == 4 is true, the caller asked you to produce pretty-printed output. Note that this is expressly not a public part of Debug/Formatter's interface, so the Rust gods could change this the moment I write this.

The best way to do this is to just use debug builders. This way, you don't have to care if pretty-printing is requested.

> # Copy and Clone
> 
> Those two traits take care of getting another object from one you already have.

duplicating?

> There are exactly two reasons not to implement Copy: Either your type cannot be Copyable, because it contains references, or your type is so big that copying it would be prohibitively expensive (e.g. it could contain an [f64; 65536]).

Should probably explain (or link) auto-copy semantics (versus move).

> Clone is a more generic solution that will take care of any references. You will probably want to auto-derive it in most cases (as being able to clone values is rather useful), and only implement it manually for things like custom refcounting schemes, garbage collection or something similar.

Cloning is also explicit (to contrast it with the auto-copy semantics of copy).

> # Default

Might want to mention `MyStruct { field: value, ..Default::default() }` syntax.

> Aside: This is also the reason why HashMap does not implement Hash itself, because two equal hash maps could still store their contents in different order, resulting in different hashes, which would break the hashing contract.

`HashMap` could implement hash if the values implemented hash (and eq). You just have to make sure the order doesn't change the hash value. For example, you could create a vector of `(hash(key), hash(value))` tuples, sort that, and then hash it. Of course, this would be kind of slow.

**Comment by llogiq** [comment]
Thank you for your Comments!
- Regarding OIBIT, perhaps that's historical and they used to be opt-in. I will try to research this, if I cannot come up with a convincing explanation, I'll remove it.
- `Eq` has a `fn assert_receiver_is_total_eq(&self) {}`. It's hidden from the docs and its only use is to be able to ensure that the receiver has successfully derived the trait. Perhaps I should add this to avoid confusion.
- `IndexMut`: Good point! I'll see how I can add this.
- Debug Builders: Another good point. Probably the best way to manually implement `Debug`
- Copy vs. move semantics: Yes, I should at least link this – and this is actually a third reason not to implement `Copy`: If you want move semantics.
- `Default`: Agreed. I will add it.
- `HashMap`: That would require the keys to implement an `Ord`ering. So, apart from being kind of slow, it would also not work in the general case.

**Comment by Stebalien** [comment]
On July 28, 2015 11:19:48 PM PDT, llogiq notifications@github.com wrote:

> Thank you for your Comments!
> - Regarding OIBIT, perhaps that's historical and they used to be
>   opt-in. I will try to research this, if I cannot come up with a
>   convincing explanation, I'll remove it.
> - `Eq` has a `fn assert_receiver_is_total_eq(&self) {}`. It's hidden
>   from the docs and its only use is to be able to ensure that the
>   receiver has successfully derived the trait. Perhaps I should add this
>   to avoid confusion.

Sounds like an internal that shouldn't be relied upon but I might be wrong.

> - `IndexMut`: Good point! I'll see how I can add this.
> - Debug Builders: Another good point. Probably the best way to manually
>   implement `Debug`
> - Copy vs. move semantics: Yes, I should at least link this – and this
>   is actually a third reason not to implement `Copy`: If you want move
>   semantics.
> - `Default`: Agreed. I will add it.
> - `HashMap`: That would require the keys to implement an `Ord`ering.
>   So, apart from being kind of slow, it would also not work in the
>   general case. 

Order by hash of the key concatenated with the hash of the value. Numbers can always be ordered.

**Comment by llogiq** [comment]
> Sounds like an internal that shouldn't be relied upon but I might be wrong.

Yes, I would also not want to rely on that function being available, but I still find it's existence strangely interesting. :smile: I shall add a word of warning.

> Order by hash of the key concatenated with the hash of the value. Numbers can always be ordered.

But that would require using the same `Hasher` for both maps. So either the HashMap would need to use a _different_ `Hasher` than the one that it is configured to use, or two hash maps with different hashers wouldn't necessarily be equal, even if their contents are.

**Comment by Stebalien** [comment]
>  But that would require using the same Hasher for both maps. So either the HashMap would need to use a different Hasher than the one that it is configured to use, or two hash maps with different hashers wouldn't necessarily be equal, even if their contents are.

You use the hasher for the outer map. This isn't inconsistent because the `Hash` trait doesn't even care that we're dealing with a `HashMap` so the `HashMap`'s hasher isn't even relevant. Basically, you treat the `(key, value)` pairs as struct members. (Although personally, I'd just XOR the hashes of the `(key, value)` pairs together after hashing so we don't have to care about sorting.)

**Comment by llogiq** [comment]
True. But then the hasher used for sorting would have to be a _perfect hash_er, else you may get same hashes for different values, which could then be sorted either way.

This discussion is getting very abstruse – I like it! :smile:

**Comment by Stebalien** [comment]
Sorry, I assumed you would be hashing the sorted hashes together so it wouldn't make a difference. That is, given:

```
tuple -> hash
("a", 1) -> 2
("b", 2) -> 99
("z", 3) -> 99
```

If you then hash `(2, 99, 99)`. It doesn't make a difference which `99` comes first. (although, again, I'd just XOR the hashes so we don't need to sort/allocate because XOR is commutative).

**Comment by llogiq** [comment]
Yeah, that makes sense, but XOR is a rather weak hash functions, so you're trading hash quality for performance. Then again, all the cases I've seen so far where Maps were used as keys in other Maps have been pathological cases where the programmer didn't know what they were doing.

**Comment by Stebalien** [comment]
As long as the original hash function is decent, the tuple hashes should be uniformly random so the XORs of the tuple hashes should be uniformly random. Unfortunately, upon further inspection of the Hash API, this method would either require that the hasher implement `Hasher + Clone` (because you would need to independently hash the key/value pairs) which the `Hash` trait doesn't require or use a the hashmap's hasher (which kind of violates the spec).

Alternatively, you actually just use the identity function as a perfect hash function for sorting (by implementing a custom hasher that serializes its input into some side buffer). Regardless, none of these methods are particularly efficient.

**Comment by Stebalien** [comment]
And I also happen to love abstruse discussions if that isn't already clear :smile:.

**Comment by llogiq** [comment]
> this method would either require that the hasher implement Hasher + Clone (because you would need to independently hash the key/value pairs) which the Hash trait doesn't require or use a the hashmap's hasher (which kind of violates the spec).

Yeah, I noticed that earlier, I did not write about it because it seemed obvious at that moment. Note that we cannot even use the fact that Robin Hood Hashing kinda sorts the key by their truncated hash value, because the truncation may happen to different sizes.

> And I also happen to love abstruse discussions if that isn't already clear :smile:.

Who would have thought? A congenial mind... :smiley:
