### ISSUE TITLE
Ambiguous sentence in 'From / Into article'

### ISSUE THREAD

**Issue by Seeker14491** [llogiq/llogiq.github.io#8]
In the ['From / Into article'](https://llogiq.github.io/2015/11/27/from-into.html), when I read the sentence "In our case, we also have a `Blob` type which contains a `Bar` and a `Buzz` type which can be converted to a `Bar`.", I interpreted this incorrectly as:

``` rust
struct Blob {
    bar: Bar,
    buzz: Buzz,
}
```

The correct code is just below, but I was reading on my phone, where it's not immediately visible. Perhaps the sentence could be reworded, or the code positioned first, followed by the explanation?

**Comment by llogiq** [comment]
Thanks for pointing that out. I'm currently on mobile, but will fix it as soon as I get to my PC.

**Comment by llogiq** [comment]
Thanks again.
