### ISSUE TITLE
Unbalanced `< >` in types article

### ISSUE THREAD

**Issue by Seeker14491** [llogiq/llogiq.github.io#9]
The snippet `<<Not<True>::Output as Same<False>>::Output` on [this line](https://github.com/llogiq/llogiq.github.io/blame/b16f76082b57fd589c7b1e7593eb91ebd3f6cd6a/_posts/2015-12-12-types.md#L96) has unbalanced `< >`.

**Comment by llogiq** [comment]
Thanks for pointing that out. Will fix shortly.

**Comment by Seeker14491** [comment]
Also `<Not<True>::Output::to_ternary()` [here](https://github.com/llogiq/llogiq.github.io/blame/b16f76082b57fd589c7b1e7593eb91ebd3f6cd6a/_posts/2015-12-12-types.md#L120)

**Comment by llogiq** [comment]
Thanks again!
